### ISSUE TITLE
Problema seguridad

### ISSUE THREAD

**Issue by ncalderini** [caramelpoint/mercado_pago_integration#1]
Buenas! Antes que nada muy buen aporte, pude incorporar el checkout en mi aplicación sin problemas,

El único inconveniente que vi es que están dependiendo de la librería `mercadopago_sdk: ^1.1.3`
Esta lib creo tiene un problema grave de seguridad que expone el `ACCESS_TOKEN` de la app de MercadoPago a cualquiera que decompile la app mobile y puede hacer cualquier acción en nombre de la app.

Es posible que se elimine el `access_token` como parámetro obligatorio y que sea un backend propio el que instancie la preferencia y nos devuelva su id? Creo que es un paso obligatorio que pide MercadoPago pero los que hicieron la otra lib del SDK lo quisieron saltar.

Saludos!

**Comment by henriqueuller** [comment]
¿Algún comentario sobre esta situación?

Muy buena contribución y muchas gracias!

**Comment by ncalderini** [comment]
> ¿Algún comentario sobre esta situación?
> 
> Muy buena contribución y muchas gracias!

@henriqueuller En este [video](https://www.youtube.com/watch?v=AAROFgR5Pzo) explica un poco mas el problema, termine usando esa lib

**Comment by henriqueuller** [comment]
@ncalderini Muchas gracias, miraré y veré cómo se ve la implementación.

**Comment by facucaramelpoint** [comment]
@ncalderini @henriqueuller Gracias por los comentarios. 
Se puede seguir usando esta versión de la lib, para evitar el problema que mencionas,  el `access_token` deberia venir de alguna API del backend de tu sistema, para evitar que al decompilar la app obtengan el `access_token`. Esa es la forma que la usamos actualmente a la lib.

**Comment by ncalderini** [comment]
@facucaramelpoint Gracias por la respuesta. Si, esa seria una solución para el ataque por decompilación pero cuidado si interceptan los paquetes http que envia/recibe la app con algún mitm, si el `access_token` viaja sin ningún tipo de seguridad cae en la misma. 

Saludos!

**Comment by facucaramelpoint** [comment]
Tal cual @ncalderini el `access_token` debería estar encriptado. 

De todos modos, trabajaremos en una nueva versión de la lib con algún fix para el problema.

Saludos
